version: "3"

services:

  mysql-database:
    build:
      context:    ./docker
      dockerfile: Dockerfile
      args:
        USER_ID:  "${MYSQL_GROUP_ID}"
        GROUP_ID: "${MYSQL_GROUP_ID}"
    container_name: mysql-database
    networks:
      - traefik
    restart:        always
    command:        mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - "${MYSQL_PATH}:/var/lib/mysql"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.service=mysql"
      - "traefik.tcp.routers.mysql.tls=false"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=mysql"
      - "traefik.tcp.routers.mysql.entryPoints=mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "${MYSQL_TZ}"

networks:
  traefik:
    external:
      name: traefik